# Generated by Django 5.2.1 on 2025-06-03 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exp_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="income",
            old_name="monthly_income",
            new_name="interest_rate",
        ),
        migrations.AddField(
            model_name="income",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="income",
            name="long_term",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="income",
            name="monthly_incomes",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date(2025, 6, 3)),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(default=datetime.date(2025, 6, 3)),
        ),
    ]
