# Generated by Django 5.2.5 on 2025-08-23 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exp_tracker", "0002_rename_monthly_income_income_interest_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=datetime.date(2025, 8, 23)),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(default=datetime.date(2025, 8, 23)),
        ),
    ]
