# Generated by Django 5.2.5 on 2025-08-25 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exp_tracker", "0003_alter_expense_date_alter_income_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
